# Site settings
title: François Baldassari
email: self@franc0is.com
description: > # this means to ignore newlines until "baseurl:"
  François Baldassari's home on the web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://franc0is.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
